version: '3.7'
services:

  php_apache_symfony:
    build:
      context: ./
      dockerfile: docker/php/dockerfile
    container_name: php_apache_symfony
    ports:
      - 80:80
    environment:
      SERVICE_NAME: php_apache_symfony
    volumes:
      - .:/var/www/html
    links:
      - postgres_symfony

  postgres_symfony:
    build:
      context: ./
      dockerfile: docker/postgres/dockerfile
    container_name: postgres_symfony
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      SERVICE_NAME: postgres_symfony
    ports:
      - 5432:5432
    volumes:
      - ./logs/postgres:/var/log/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    links:
      - postgres_symfony
